# Copyright 2025 The Torch-Spyre Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging


import torch
from .logging_utils import get_inductor_logger
from torch._inductor.ir import (
    ComputedBuffer,
    FallbackKernel,
    FixedLayout,
    InputBuffer,
    MultiOutput,
    Pointwise,
    Reduction,
    StorageBox,
    TensorBox,
)
from torch._inductor.scheduler import (
    BaseSchedulerNode,
    SchedulerNode,
    ExternKernelSchedulerNode,
    NopKernelSchedulerNode,
)
from torch._inductor.virtualized import V

from torch_spyre._C import (
    SpyreTensorLayout,
    get_device_dtype,
    get_elem_in_stick,
)
from .errors import Unsupported
from .constants import MATMUL_REDUCTION_OP, BATCH_MATMUL_OP
from .ir import FixedTiledLayout
from .pass_utils import (
    SchedNodeArg,
    get_mem_deps,
    host_coordinates,
    device_coordinates,
)
from .views import matching_dim
from .insert_nodes import print_node, dump_ir


logger = get_inductor_logger("stickify")

aten = torch.ops.aten
spyreop = torch.ops.spyre


def same_device_size(t1: torch.dtype, t2: torch.dtype) -> bool:
    return get_elem_in_stick(t1) == get_elem_in_stick(t2)


def compute_device_size(host_size: list, dim_map: list, stick_size: int = 64) -> list:
    """Compute device_size from host_size and a target dim_map.

    The C++ SpyreTensorLayout constructor only produces a correct stride_map
    when the host is contiguous in the given dim_order.  We replicate the logic
    here to handle non-contiguous strides (e.g. after a transpose).

    Each non-stick device dim gets the full size of its host dim, except when
    it shares a host dim with the stick — then it gets host_size // stick_size.
    The last (stick) device dim is always stick_size (64 at fp16).
    """
    print ("MRA2: compute_device_size: host_size:", host_size, "dim_map:", dim_map)
    stick_host_dim = dim_map[-1]
    result = []
    for j in range(len(dim_map) - 1):
        h = dim_map[j]
        if h == stick_host_dim:
            result.append(host_size[h] // stick_size)
        else:
            result.append(host_size[h])
    result.append(stick_size)
    return result


def dim_map_to_stride_map(host_stride: list, device_size: list, dim_map: list) -> list:
    """Compute stride_map from host_stride and tiling geometry (device_size, dim_map).

    Python port of the C++ static function dim_map_to_stride_map, which is not
    exposed to Python.  Iterates backwards, accumulating the product of inner
    device sizes for each host dim so that higher-dimensional cases with a host
    dim appearing 3+ times in dim_map are handled correctly.
    """
    print ("MRA2: dim_map_to_stride_map: host_stride:", host_stride, "device_size:", device_size, "dim_map:", dim_map)
    n = len(device_size)
    stride_map = [-1] * n
    last_stride: dict[int, int] = {}
    for j in range(n - 1, -1, -1):
        d = dim_map[j]
        if d == -1:
            stride_map[j] = -1
        elif d not in last_stride:
            stride_map[j] = host_stride[d]
            last_stride[d] = stride_map[j] * device_size[j]
        else:
            stride_map[j] = last_stride[d]
            last_stride[d] = stride_map[j] * device_size[j]
    return stride_map


def pointwise_layout(n: SchedulerNode, args: list[SchedNodeArg], permute_needed: dict) -> FixedTiledLayout:
    pw: Pointwise = n.node.data
    output: FixedLayout = n.node.get_layout()
    output_dep = next(iter(n.read_writes.writes))
    origin_node = next(iter(pw.origins))
    op = origin_node.target

    if len(args) == 1:
        x = args[0]
        match op:
            case aten.clone.default:
                # Clone is generated by an explicit `contiguous()`; on spyre that means use the default row major tiling.
                stl = SpyreTensorLayout(
                    output.size,
                    output.stride,
                    output.dtype,
                    list(range(len(output.size))),
                )
                return FixedTiledLayout(
                    output.device, output.dtype, output.size, output.stride, stl
                )

            case spyreop.restickify.default:
                # MRA TEMP CODE
                # stride_order = origin_node.args[1]
                # if stride_order == [0, 1]:
                #     stl = SpyreTensorLayout([2, 256, 64], [0,1,0], [16384, 1, 256], get_device_dtype(output.dtype))
                # else:
                #     # stl = SpyreTensorLayout([2, 256, 64], [1,0,1], [64, 128, 1], get_device_dtype(output.dtype))
                #     stl = SpyreTensorLayout([2, 256, 64], [0,1,0], [8192, 1, 128], get_device_dtype(output.dtype))

                # return FixedTiledLayout(
                #     output.device, output.dtype, output.size, output.stride, stl
                # )
                assert(False)
                pass

            case _:
                x_stl = x.layout.device_layout
                in_coords = host_coordinates(x.layout, x.dep)
                out_coords = host_coordinates(output, output_dep)
                if (
                    in_coords == out_coords
                    and x.dep.index == output_dep.index
                    and same_device_size(x.layout.dtype, output.dtype)
                ):
                    # Input and output tensors are being accessed identically and elem size is the same.
                    # We can simply propagate the device_layout.
                    stl = SpyreTensorLayout(
                        x_stl.device_size,
                        x_stl.dim_map,
                        x_stl.stride_map,
                        get_device_dtype(output.dtype),
                    )
                else:
                    # TODO: Once we eliminate the dim_map from the STL,
                    #       we should be able to preserve the input stride_map
                    #       unless the operation is changing elems_per_stick.
                    #       Until then, use the default layout for a mostly row major dimension
                    #       ordering, adjusted to put the stick dimension last and move all
                    #       non-stick size one dimensions to the right to avoid tiling them.
                    in_device_coords = device_coordinates(x.layout, x.dep)
                    stick_expr = in_device_coords[-1]
                    maybe_stick_dim = matching_dim(out_coords, stick_expr)
                    out_stick_dim = -1 if maybe_stick_dim is None else maybe_stick_dim
                    dim_order = [
                        d
                        for d in range(len(output.size))
                        if d != out_stick_dim and out_coords[d] != 0
                    ]
                    dim_order += [
                        d
                        for d in range(len(output.size))
                        if d != out_stick_dim and out_coords[d] == 0
                    ]
                    dim_order += [out_stick_dim]
                    stl = SpyreTensorLayout(
                        output.size, output.stride, output.dtype, dim_order
                    )

                return FixedTiledLayout(
                    output.device, output.dtype, output.size, output.stride, stl
                )

    elif op == spyreop.layernormnorm.default:
        # Output layout is determined by layout of first argument only
        x = args[0]
        x_stl = x.layout.device_layout
        if x.layout.size != output.size or x.layout.stride != output.stride:
            raise Unsupported(
                f"views not supported for spyre.layernormnorm({x.layout.size})=>{output.size}) "
            )
        stl = SpyreTensorLayout(
            x_stl.device_size, x_stl.dim_map, x_stl.stride_map, x_stl.device_dtype
        )
        return FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )
    else:
        for i, arg in enumerate(args):
            print(f"MRA ARG: {i} layout: {arg.layout}, dep: {arg.dep}")
        in_coords = [host_coordinates(arg.layout, arg.dep) for arg in args]
        in_device_coords = [device_coordinates(arg.layout, arg.dep) for arg in args]
        out_coords = host_coordinates(output, output_dep)

        print ("IN COORDS:", in_coords)
        print ("IN DEVICE COORDS:", in_device_coords)
        print ("OUT COORDS:", out_coords)
        # Stick compatability check.
        # For all tensors whose stick dimension is being iterated over,
        # the indexing expression must be identical.
        stick_exprs = set()
        for idc in in_device_coords:
            if idc[-1] != 0:
                stick_exprs.add(idc[-1])
        stick_expr = next(iter(stick_exprs))

        if len(stick_exprs) > 1:
            # This is a legal PyTorch operation that we cannot execute without inserting restickify operations.
        
            for arg in args:
                print ("ARG:", arg)

            print ("NODE BEFORE RESTICKIFY:")
            print_node(n)
            print (f"WARNING: Spyre limitation: pointwise op with nonuniform stick indexing: {stick_exprs}.  Injecting restickify")
        
            # For now leave arg 0 and permute all others that have a conflict
            stick_expr = in_device_coords[0][-1]
            print ("MRA1: USING STICK EXPR:", stick_expr)

            for arg_i, (ic, idc, arg) in enumerate(zip(in_coords[1:], in_device_coords[1:], args[1:]), start=1):
                dl = arg.layout.device_layout
                print (f"MRA2: ARG {arg_i} ({arg.dep.name}) coords: {ic}, device coords: {idc}, stick expr: {stick_expr}, arg: {arg}")
                new_stick_dim = matching_dim(ic, stick_expr)
                print (f"MRA2: New stick dim for arg {arg_i} is: {new_stick_dim}")
                orig_dim_map = arg.layout.device_layout.dim_map
                old_stick_dim = orig_dim_map[-1]

                # Swap the new stick dim and old stick dim
                new_dim_map = [new_stick_dim if x == old_stick_dim else old_stick_dim if x == new_stick_dim else x for x in orig_dim_map]
                print (f"MRA2: Computed new dim map for {arg_i} is: {new_dim_map}")

                if idc[-1] != stick_expr:
                    # host_stride[d] = coeff of the dep var whose range matches output.size[d]
                    # For each output dim, extract how many elements the arg's buffer advances
                    # per step in that dim — i.e. the coefficient of that dim's loop variable in dep.index.
                    arg_host_stride = [int(arg.dep.index.coeff(next(iter(out_coords[d].free_symbols)))) for d in range(len(output.size))]
                    print (f"MRA2: ARG {arg_i} has incompatible stick expr. Permuting. arg_host_stride={arg_host_stride}")
                    # stl = SpyreTensorLayout([2, 256, 64], [0,1,0], [8192, 1, 128], get_device_dtype(output.dtype))
                    # target_layout = FixedTiledLayout(output.device, output.dtype, [256,128], [128,1], stl)

                    # # Works for
                    # #    x.t() + y
                    # #    x.t() + y + z
                    # # stl = SpyreTensorLayout([2,256,64], new_dim_map, [8192, 1, 128], dl.device_dtype) # worked
                    # # Works for x.t() + y, x.t() + y + z
                    # stl = SpyreTensorLayout([4, 128, 64], new_dim_map, [8192, 1, 128], dl.device_dtype)
                    # target_layout = FixedTiledLayout(output.device, output.dtype, output.size, [128,1], stl)

                    # # Works for y + x.t()
                    # stl = SpyreTensorLayout([2,256,64], new_dim_map, [16384, 1, 256], dl.device_dtype)
                    # target_layout = FixedTiledLayout(output.device, output.dtype, output.size, [1, 256], stl)

                    # STL (device size and stride map) are function of dim map and device layout 
                    device_size = compute_device_size(list(arg.layout.size), new_dim_map)
                    stride_map = dim_map_to_stride_map(list(arg.layout.stride), device_size, new_dim_map)
                    stl = SpyreTensorLayout(device_size, new_dim_map, stride_map, dl.device_dtype)
                    # FixedTileLayout incorporates python's view using the host stride
                    target_layout = FixedTiledLayout(output.device, output.dtype, output.size, arg_host_stride, stl)

                    print ("MRA2: Using computed layout:", target_layout)
                    if n not in permute_needed:
                        permute_needed[n] = []
                    permute_needed[n].append({"arg_index": arg_i, "target_layout": target_layout})

            # stl = SpyreTensorLayout([2, 256, 64], [0,1,0], [16384, 1, 256], get_device_dtype(output.dtype)) 
            # target_layout = FixedTiledLayout(
            #     output.device, output.dtype, [256,128], [1,256], stl
            # )
            # if chosen_arg == 0:
            #     # If we mess with arg 0 we must return this layout. Otherwise it'll create a different one below that
            #     # is incompatible with the new layout of arg 0 
            #     return target_layout


        # If the indexing and device element size are identical
        # across all inputs and the output we can just propagate the device layout.
        can_use_same_layout = True
        for arg, arg_coors in zip(args, in_coords):
            if (
                arg_coors != out_coords
                or arg.dep.index != output_dep.index
                or not same_device_size(arg.layout.dtype, output.dtype)
            ):
                can_use_same_layout = False
                break

        if can_use_same_layout:
            template_stl = args[0].layout.device_layout
            stl = SpyreTensorLayout(
                template_stl.device_size,
                template_stl.dim_map,
                template_stl.stride_map,
                get_device_dtype(output.dtype),
            )
        else:
            # Use row major adjusted to put stick dimension last
            # and move all non-stick size one dimensions to the right to avoid tiling them.
            if len(stick_exprs) == 0:
                maybe_stick_dim = None
                out_stick_dim = -1
            else:
                maybe_stick_dim = matching_dim(out_coords, stick_expr)
                out_stick_dim = -1 if maybe_stick_dim is None else maybe_stick_dim

            dim_order = [
                d
                for d in range(len(output.size))
                if d != out_stick_dim and out_coords[d] != 0
            ]
            dim_order += [
                d
                for d in range(len(output.size))
                if d != out_stick_dim and out_coords[d] == 0
            ]
            dim_order += [out_stick_dim]
            stl = SpyreTensorLayout(output.size, output.stride, output.dtype, dim_order)
            print ("DAVE's code computed DIM ORDER: ", dim_order)
            print ("DAVE's code computed STL: ", stl)

        result = FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )

        if logger.isEnabledFor(logging.DEBUG):
            input_info = ", ".join(
                [f"in{i}:{list(arg.layout.size)}" for i, arg in enumerate(args)]
            )
            logger.debug(
                f"{op.__name__} layout: {input_info} -> out:{list(result.size)}, "
                f"device_size={list(result.device_layout.device_size)}"
            )

        return result


def reduction_layout(n: SchedulerNode, args: list[SchedNodeArg]) -> FixedTiledLayout:
    red: Reduction = n.node.data
    output: FixedLayout = n.node.get_layout()
    output_dep = next(iter(n.read_writes.writes))
    if (
        red.reduction_type == MATMUL_REDUCTION_OP
        or red.reduction_type == BATCH_MATMUL_OP
    ):
        x = args[0]
        y = args[1]
        x_coords = host_coordinates(x.layout, x.dep)
        x_dev_coords = device_coordinates(x.layout, x.dep)
        y_coords = host_coordinates(y.layout, y.dep)
        y_dev_coords = device_coordinates(y.layout, y.dep)
        out_coords = host_coordinates(output, output_dep)
        x_stick_expr = x_dev_coords[-1]
        y_stick_expr = y_dev_coords[-1]
        x_stick_dim = matching_dim(x_coords, x_stick_expr)
        y_stick_dim = matching_dim(y_coords, y_stick_expr)
        if x_stick_dim is None or y_stick_dim is None:
            raise Unsupported(
                f"{red.reduction_type}: failed to map stick_dims to host coords"
            )

        if (
            x_stick_dim != len(x.layout.size) - 1
            or y_stick_dim != len(y.layout.size) - 1
        ):
            # TODO: This is a legal PyTorch operation that we cannot execute without inserting restickify operations.
            raise Unsupported(
                f"Spyre limitation: {red.reduction_type} requires restickify"
            )
        out_stick_dim = matching_dim(out_coords, y_stick_expr)
        if out_stick_dim is None:
            raise Unsupported(
                f"{red.reduction_type}: failed to map output stick_dim to host coords {out_coords} {y_stick_expr}"
            )

        out_dims = len(output.size)
        out_dim_order = list(range(out_dims - 2))
        if out_stick_dim == out_dims - 1:
            out_dim_order = out_dim_order + [out_dims - 2, out_dims - 1]
        else:
            out_dim_order = out_dim_order + [out_dims - 1, out_dims - 2]
        stl = SpyreTensorLayout(output.size, output.stride, output.dtype, out_dim_order)
        return FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )
    elif red.reduction_type == "exx2":
        x = args[0]
        x_coords = host_coordinates(x.layout, x.dep)
        x_dev_coords = device_coordinates(x.layout, x.dep)
        x_stick_expr = x_dev_coords[-1]
        x_stick_dim = matching_dim(x_coords, x_stick_expr)
        if x_stick_dim is None or x_stick_dim != len(x.layout.size) - 1:
            # TODO: Insert a restickify to enable the operation to be performed
            raise Unsupported(f"exx2: illegal device layout {x.layout}")

        dim_map = list(range(len(output.size))) + [-1]
        stl = SpyreTensorLayout(output.size, output.stride, output.dtype, dim_map)
        return FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )
    else:
        x = args[0]
        x_coords = host_coordinates(x.layout, x.dep)
        x_dev_coords = device_coordinates(x.layout, x.dep)
        out_coords = host_coordinates(output, output_dep)
        x_stick_expr = x_dev_coords[-1]
        out_stick_dim = matching_dim(out_coords, x_stick_expr)
        if out_stick_dim is None:
            out_dim_order = list(range(len(output.size))) + [-1]
        else:
            out_dim_order = [
                d for d in list(range(len(output.size))) if d != out_stick_dim
            ]
            out_dim_order = out_dim_order + [out_stick_dim]
        stl = SpyreTensorLayout(output.size, output.stride, output.dtype, out_dim_order)
        result = FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )

        if logger.isEnabledFor(logging.DEBUG):
            logger.debug(
                f"{red.reduction_type} layout: in:{list(args[0].layout.size)} -> out:{list(result.size)}, "
                f"device_size={list(result.device_layout.device_size)}"
            )

        return result


def generic_layout(n: ExternKernelSchedulerNode) -> FixedTiledLayout:
    output: FixedLayout = n.node.get_layout()
    # Use the generic stick format
    stl = SpyreTensorLayout(output.size, output.dtype)
    return FixedTiledLayout(
        output.device, output.dtype, output.size, output.stride, stl
    )


def propagate_spyre_tensor_layouts(
    nodes: list[BaseSchedulerNode],
) -> list[BaseSchedulerNode]:
    # Convert InputBuffers from FixedLayout to FixedTiledLayouts
    if len(V.graph.graph_input_names) > 0:
        for name, real_input in zip(V.graph.graph_input_names, V.get_real_inputs()):
            if isinstance(real_input, torch.Tensor):
                stl = real_input.device_tensor_layout()
                if stl is None:
                    # All spyre tensors are created with device layouts.
                    # Therefore we expect all graph inputs to have them.
                    raise Unsupported(
                        f"missing device_tensor_layout on graph input {name}"
                    )

                tb = V.graph.graph_inputs[name]
                if (
                    not isinstance(tb, TensorBox)
                    or not isinstance(tb.data, StorageBox)
                    or not isinstance(tb.data.data, InputBuffer)
                ):
                    raise Unsupported(
                        "graph input {name} is not a TensorBox(StorageBox(InputBuffer))"
                    )
                ptl = tb.data.data.layout
                if not isinstance(ptl, FixedLayout):
                    raise Unsupported("graph input {name} does not have a FixedLayout")
                tb.data.data.layout = FixedTiledLayout(
                    ptl.device, ptl.dtype, ptl.size, ptl.stride, stl
                )

    # Nodes are in topological order (guarenteed by caller).
    # Visit them and use the inputs' FixedTiledLayouts and the operation being
    # performed by the node to convert its output FixedLayout to a FixedTiledLayout.

    permute_needed: dict[BaseSchedulerNode, dict[str, Any]] = {}

    it = iter(nodes)
    for n in it:
        if isinstance(n, SchedulerNode) and isinstance(n.node, ComputedBuffer):
            n.node.decide_layout()
            if isinstance(n.node.data, Pointwise):
                output_layout = pointwise_layout(n, get_mem_deps(n), permute_needed)
                n.node.layout = output_layout
            elif isinstance(n.node.data, Reduction):
                output_layout = reduction_layout(n, get_mem_deps(n))
                n.node.layout = output_layout
            else:
                logger.warning(f"Warning: unhandled node type {type(n.node)}")
        elif isinstance(n, ExternKernelSchedulerNode):
            if isinstance(n.node, FallbackKernel):
                n = next(it, None)
                if not (
                    isinstance(n, ExternKernelSchedulerNode)
                    and isinstance(n.node, MultiOutput)
                ):
                    raise RuntimeError("FallbackKernel must be followed by MultiOutput")

                output_layout = generic_layout(n)
                n.node.layout = output_layout
            else:
                logger.warning(f"unhandled node type {type(n.node)}")
        elif isinstance(n, NopKernelSchedulerNode):
            output_layout = generic_layout(n)
            n.node.layout = output_layout
        else:
            logger.warning(f"unhandled scheduler node type {type(n)}")
    print ("STICKIFY: after layout propagation:")
    dump_ir(nodes)

    print ("MRA5: permute needed:", permute_needed)
    return nodes, permute_needed
